- name: frontend 
  hosts: all
  become: yes
  tasks:
    - name: install the nignx
      ansible.builtin.dnf:
        name: nignx
        state: present
    - name: copying the expense.conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: delete the directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: create the directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory    
    - name: download and extract the application
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: start the nginx
      ansible.builtin.systemd:
         name: nginx
         state: restarted
         enabled: yes