    - name: disable the nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable the nodejs 18
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: copy the backend.service file
      ansible.builtin.template:   
       src: backend.service
       dest: /etc/systemd/system/backend.service
    - name: install the nodejs
      ansible.builtin.dnf:  
        name: nodejs
        state: present   
    - name: adding the user
      ansible.builtin.user:
        name: expense
    - name: import commom role- app-prereq
      ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq
      vars:
        app_dir: /app 
        component: backend
    - name: Install the dependencies
      ansible.builtin.shell:
        cmd: npm install
        chdir: /app
    - name: install client service
      ansible.builtin.dnf:
       name: mysql
       state: present
    - name: Load schema
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }}
       -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} 
       -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql  
    - name: Backend service
      ansible.builtin.systemd:
       name: backend
       state: restarted
       enabled: yes
       daemon-reload: yes
    - name: import the ELK
      ansible.builtin.import_role:
       name: ELK
       tasks_from: filebeats   



