    - name: install the nignx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: copying the expense.conf
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: import commom role- app-prereq
      ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq
      vars:
        app_dir: /usr/share/nginx/html
        component: frontend 

    - name: start the nginx
      ansible.builtin.systemd:
         name: nginx
         state: restarted
         enabled: yes
    - name: import the ELK
      ansible.builtin.import_role:
       name: ELK
       tasks_from: filebeats 
    - name: import the prometheus
      ansible.builtin.import_role:
       name: prometheus
       tasks_from: node-exporter

