    - name: install the nignx
      ansible.builtin.dnf:
        name: ngnx
        state: present
    - name: copying the expense.conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
   - name: import commom role- app-prereq
     ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq
      vars:
        app_dir: /usr/share/nginx/html
        component: frontend 

    - name: start the nginx
      ansible.builtin.systemd:
         name: nginx
         state: restarted
         enabled: yes