- name: copy rsys.log conf file
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{component}}.conf
  when: is_rsyslog_needed
  
- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted        
  when: is_rsyslog_needed  
- name: copy the elastic repo file
  ansible.builtin.template:
   src: elasticsearch.repo    
   dest: /etc/yum.repos.d/elasticsearch.repo
- name: install the filebeat
  ansible.builtin.dnf:
   name: filebeat
   state: present  

- name: copy filebeat configuration
  ansible.builtin.template:
    src: filebeats.yml
    dest: /etc/filebeat/filebeat.yml
- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted 
    enabled: yes    
