- name: copy the elastic repo file
  ansible.builtin.template:
   src: elasticsearch.repo    
   dest: /etc/yum.repos.d/elasticsearch.repo
- name: install the filebeat
  ansible.builtin.dnf:
   name: filebeat
   state: present   