    - name: disable mysql
      ansible.builtin.shell: dnf module disable mysql -y
    - name: copying the repo file
      ansible.builtin.template: 
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: installing the mysql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    - name: start mysql server
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: set the password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('amazon.aws.aws_ssm', 'mysql.{{env}}.DB_PASS', region='us-east-1' ) }}