- name: copy the config file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
- name: copy the alert rules
  ansible.builtin.template:
    src: alertrules.yml
    dest: /opt/prometheus/alertrules.yml    
- name: restart the premotheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes    
