groups:
- name: node_exporter
  labels:
    team: myteam
  rules:
  - alert: instance down alert
    expr: up < 0
    for: 1m
    keep_firing_for: 5m
    labels:
      severity: critical
    annotations:
      summary: instance down alert